---
author: "不知名水豚"
title: "前端? 後端? 大數據? 解析工程師的密碼"
output:
  html_document:
    number_sections: yes
    highlight: tango
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'hold', warning = F, message = F, fig.align='center')
```




```{r, echo=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(rvest)
library(httr)
library(stringr)
```

前端
=========================


## 前端資料

```{r}
front <- readr::read_csv("../data/front.csv")
front_sim <- front %>% select("local", "salary", "department", "tools")
DT::datatable(front_sim)
```


## 前端工程師科系要求

```{r}
##資料讀取與清理
product <- read_csv("../data/front.csv") %>%
    filter(salary != "待遇面議")
list_dep_product <- strsplit(product$department, "、")
vec_dep_product <- unlist(list_dep_product)
vec_dep_product <- gsub("\\s?資訊工程相關\\s?", "資訊工程相關", vec_dep_product)
vec_dep_product <- gsub("\\s?資訊管理相關\\s?", "資訊管理相關", vec_dep_product)
vec_dep_product <- gsub("\\s?電機電子工程相關\\s?", "電機電子工程相關", vec_dep_product) 
vec_dep_product[vec_dep_product == "應用數學相關" |
                    vec_dep_product == "數學及電算機科學學科類"] <- "其他數學及電算機科學相關"
vec_dep_product[vec_dep_product == "自然科學學科類" |
                    vec_dep_product == "藝術學科類" |
                    vec_dep_product == "數理統計相關" |
                    vec_dep_product == "商業及管理學科類"|
                    vec_dep_product == "其他工程相關" |
                    vec_dep_product == "工業管理相關" ] <- "其他相關科系"
vec_dep_product[vec_dep_product == " 不拘 "] <- "不拘"

productdt <- data.table(product)
product_m <- productdt[grepl('月薪',salary)] #將年薪資料去除

##建立提及次數dataframe
df_dep_product <- data.frame(table(vec_dep_product))
df_dep_product <- df_dep_product %>%
    arrange(desc(Freq)) %>%
    mutate(perc = round(Freq/sum(Freq)*100)) %>%
    rename(科系 = vec_dep_product)

##作長條圖
product_bar <- ggplot(df_dep_product) +
    geom_bar(aes(x = perc , y = reorder(科系, -perc)), stat = "identity") +
    labs(x = "百分比(%)", y = "科系", title = "前端工程師科系要求") +
    theme(text=element_text(family="STHeiti", size=14))

plotly::ggplotly(product_bar)
```


## 前端工程師工具要求

```{r}
#三個類型工程師

#資料讀取與清理
back_t <- read_csv("../data/back.csv")
bigdata_t <- read_csv("../data/bigdata.csv")
front_t <- read_csv("../data/front.csv")

#將tools欄位中不相關的字詞去除
back_t$tools <- gsub("贊助提升專業能力", "", back_t$tools)
bigdata_t$tools <- gsub("贊助提升專業能力", "", bigdata_t$tools)
front_t$tools <- gsub("贊助提升專業能力", "", front_t$tools)

back_t$tools <- gsub(" 不拘 ", "不拘", back_t$tools)
bigdata_t$tools <- gsub(" 不拘 ", "不拘", bigdata_t$tools)
front_t$tools <- gsub(" 不拘 ", "不拘", front_t$tools)

#整理出tools欄位中提及的種類和次數
list_tools_back <- strsplit(back_t$tools, "、")
list_tools_bigdata <- strsplit(bigdata_t$tools, "、")
list_tools_front <- strsplit(front_t$tools, "、")

vec_tools_back <- unlist(list_tools_back)
vec_tools_bigdata <- unlist(list_tools_bigdata)
vec_tools_front <- unlist(list_tools_front)

df_tools_back <- data.frame(table(vec_tools_back))
df_tools_bigdata <- data.frame(table(vec_tools_bigdata))
df_tools_front <- data.frame(table(vec_tools_front))

df_tools_back <- df_tools_back %>%
  arrange(desc(Freq)) %>%
  mutate(perc = Freq/160*100) %>%
  rename(tools = vec_tools_back)
df_tools_bigdata <- df_tools_bigdata %>%
  arrange(desc(Freq)) %>%
  mutate(perc = Freq/160*100) %>%
  rename(tools = vec_tools_bigdata)
df_tools_front <- df_tools_front %>%
  arrange(desc(Freq)) %>%
  mutate(perc = Freq/160*100) %>%
  rename(tools = vec_tools_front)

#去除年薪，只留月薪
back_tm <- back_t %>% filter(str_detect(salary, "月薪"))
bigdata_tm <- bigdata_t %>% filter(str_detect(salary, "月薪"))
front_tm <- front_t %>% filter(str_detect(salary, "月薪"))

#將salary欄位整理成數字並以千元為單位
vec_sal_back <- as.numeric(substr(back_tm$salary, 3, 4))
vec_sal_back[vec_sal_back == 10] <- 100
vec_sal_bigdata <- as.numeric(substr(bigdata_tm$salary, 3, 4))
vec_sal_front <- as.numeric(substr(front_tm$salary, 3, 4))

#列出較不常用的工具
df_tools_backu <- df_tools_back %>% filter(df_tools_back$Freq < 4)

vec_tools_backu <- as.character(df_tools_backu$tools)

df_tools_bigdatau <- df_tools_bigdata %>% filter(df_tools_bigdata$Freq < 2)

vec_tools_bigdatau <- as.character(df_tools_bigdatau$tools)

df_tools_frontu <- df_tools_front %>% filter(df_tools_front$Freq < 4)

vec_tools_frontu <- as.character(df_tools_frontu$tools)

#製作有無工具要求要求之向量
vec_tools_back1 <- back_tm$tools
vec_tools_bigdata1 <- bigdata_tm$tools
vec_tools_front1 <- front_tm$tools
##不拘
vec_tools_back1[vec_tools_back1 == "不拘"] <- "不拘"
vec_tools_bigdata1[vec_tools_bigdata1 == "不拘"] <- "不拘"
vec_tools_front1[vec_tools_front1 == "不拘"] <- "不拘"
##有要求
vec_tools_back1[vec_tools_back1 != "不拘"] <- "有"
vec_tools_bigdata1[vec_tools_bigdata1 != "不拘"] <- "有"
vec_tools_front1[vec_tools_front1 != "不拘"] <- "有"
##冷門要求
for(i in seq_along(back_tm$tools)){
  for(j in seq_along(vec_tools_backu)){
    if(str_detect(back_tm$tools[i], vec_tools_backu[j]) == TRUE){
      vec_tools_back1[i] <- "冷門要求"
    }
  }
}
for(i in seq_along(bigdata_tm$tools)){
  for(j in seq_along(vec_tools_bigdatau)){
    if(str_detect(bigdata_tm$tools[i], vec_tools_bigdatau[j]) == TRUE){
      vec_tools_bigdata1[i] <- "冷門要求"
    }
  }
}
for(i in seq_along(front_tm$tools)){
  for(j in seq_along(vec_tools_frontu)){
    if(str_detect(front_tm$tools[i], vec_tools_frontu[j]) == TRUE){
      vec_tools_front1[i] <- "冷門要求"
    }
  }
}

#將三種資料彙整
job <- vector("character", 354) 
for (i in(1:354)) {
  if(i<= 132) {
    job[i] <- "前端工程師"
  }
  if(i>132 & i<= 267) {
    job[i] <- "後端工程師"
  }
  if(i>267) {
    job[i] <- "大數據分析工程師"
  }
}

df_sal_t <- data.frame(Job = job,
                     Tools = c(vec_tools_front1,
                                    vec_tools_back1,
                                    vec_tools_bigdata1),
                     Salary = c(vec_sal_front,
                                vec_sal_back,
                                vec_sal_bigdata))
df_sal1_t <- df_sal_t %>%
  group_by(Job, Salary) %>%
  summarise(n = n()) %>%
  mutate(cumulative_ratio = cumsum(n/sum(n)*100))

#畫三種薪水累計比較圖
salary_line_t <- ggplot(df_sal1_t, aes(Salary, cumulative_ratio, group = Job, colour = Job)) +
  geom_line(size = 1.2) +scale_fill_brewer(palette = "Pastel1") +
  labs(x = "月薪(單位:千元)", y = "累積百分比(%)", title = "薪水比較") +
  theme(text=element_text(family="STHeiti", size=14))


#畫箱型圖
dep_boxplot_t <- ggplot(df_sal_t, aes(x = Job, y = Salary, fill = Tools)) +
  geom_boxplot() +
  facet_wrap(~Job, scale="free") +
  labs(y = "月薪(單位:千元)", fill = "工具要求", title = "工具要求薪水比較") +
  theme(text=element_text(family="STHeiti", size=14))


#取提及次數最多的工具前十名
df_tools_back10 <- head(df_tools_back, n = 10)
df_tools_bigdata10 <- head(df_tools_bigdata, n = 10)
df_tools_front10 <- head(df_tools_front, n = 10)

#畫長條圖
back_bar_t <- ggplot(df_tools_back10) +
  geom_bar(aes(x = perc , y = reorder(tools, -perc)), stat = "identity") +
  labs(x = "提及該工具的公司百分比", y = "工具", title = "後端工程師工具要求前十名") +
  theme(text=element_text(family="STHeiti", size=14))

bigdata_bar_t <- ggplot(df_tools_bigdata10) +
  geom_bar(aes(x = perc , y = reorder(tools, -perc)), stat = "identity") +
  labs(x = "提及該工具的公司百分比", y = "工具", title = "大數據工程師工具要求前十名") +
  theme(text=element_text(family="STHeiti", size=14))

front_bar_t <- ggplot(df_tools_front10) +
  geom_bar(aes(x = perc , y = reorder(tools, -perc)), stat = "identity") +
  labs(x = "提及該工具的公司百分比", y = "工具", title = "前端工程師工具要求前十名") +
  theme(text=element_text(family="STHeiti", size=14))

plotly::ggplotly(front_bar_t)

ggsave(back_bar_t, file="graph_output/back_bar_t.png", width=32, height=18, units = "cm")

ggsave(front_bar_t, file="graph_output/front_bar_t.png", width=32, height=18, units = "cm")

ggsave(bigdata_bar_t, file="graph_output/bigdata_t.png", width=32, height=18, units = "cm")

ggsave(dep_boxplot_t, file="graph_output/dep_boxplot_t.png", width=32, height=18, units = "cm")


```


後端
=========================

## 後端資料


```{r}
back <- readr::read_csv("../data/back.csv")
back_sim <- back %>% select("local", "salary", "department", "tools")
DT::datatable(back_sim)
```


## 後端工程師科系要求

  
```{r}
##資料讀取與清理
back <- read_csv("../data/back.csv") %>%
    filter(salary != "待遇面議")
list_dep_back <- strsplit(back$department, "、")
vec_dep_back <- unlist(list_dep_back)
vec_dep_back <- gsub("\\s?資訊工程相關\\s?", "資訊工程相關", vec_dep_back)
vec_dep_back <- gsub("\\s?資訊管理相關\\s?", "資訊管理相關", vec_dep_back)
vec_dep_back[vec_dep_back == "其他數學及電算機科學相關 " |
            vec_dep_back == "應用數學相關" |
            vec_dep_back == "數學及電算機科學學科類" |
            vec_dep_back == "數學及電算機科學相關"] <- "其他數學及電算機科學相關"
vec_dep_back[vec_dep_back == "運輸通信學科類"] <- "通信學類"
vec_dep_back[vec_dep_back == "工業工程相關"] <- "工程學科類" 
vec_dep_back[vec_dep_back == " 不拘 "] <- "不拘"


backdt <- data.table(back)
back_m <- backdt[grepl('月薪',salary)] #將年薪資料去除

##建立提及次數dataframe
df_dep_back <- data.frame(table(vec_dep_back))
df_dep_back <- df_dep_back %>%
    arrange(desc(Freq)) %>%
    mutate(perc = round(Freq/sum(Freq)*100)) %>%
    rename(科系 = vec_dep_back)

##作長條圖
back_bar <- ggplot(df_dep_back) +
    geom_bar(aes(x = perc , y = reorder(科系, -perc)), stat = "identity") +
    labs(x = "百分比(%)", y = "科系", title = "後端工程師科系要求") +
    theme(text=element_text(family="STHeiti", size=14))


plotly::ggplotly(back_bar)

```

## 後端工程師工具要求


```{r}
plotly::ggplotly(back_bar_t)
```


大數據
=========================

## 大數據資料
   
```{r}
bigdata <- readr::read_csv("../data/bigdata.csv")
bigdata_sim <- bigdata %>% select("local", "salary", "department", "tools")
DT::datatable(bigdata_sim)
```
   

## 大數據工程師科系要求

```{r}
##資料讀取與清理
bigdata <- read_csv("../data/bigdata.csv") %>%
    filter(salary != "待遇面議")
list_dep_bigdata <- strsplit(bigdata$department, "、")
vec_dep_bigdata <- unlist(list_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?資訊工程相關\\s?", "資訊工程相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?資訊管理相關\\s?", "資訊管理相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?電機電子工程相關\\s?", "工程相關", vec_dep_bigdata) 
vec_dep_bigdata <- gsub("\\s?其他數學及電算機科學相關\\s?", "其他數學及電算機科學相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?數學及電算機科學學科類\\s?", "其他數學及電算機科學相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?應用數學相關\\s?", "其他數學及電算機科學相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?一般數學相關\\s?", "其他數學及電算機科學相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?數理統計相關\\s?", "統計學相關", vec_dep_bigdata)
vec_dep_bigdata <- gsub("\\s?統計學相關\\s?", "統計學相關", vec_dep_bigdata)
vec_dep_bigdata[vec_dep_bigdata == " 市場行銷相關"] <- "市場行銷相關" 
vec_dep_bigdata[vec_dep_bigdata == " 商業及管理學科類" |
                    vec_dep_bigdata == "商業及管理學科類" |
                vec_dep_bigdata == " 其他商業及管理相關" |
                vec_dep_bigdata == "商業及管理學科類 " |
                vec_dep_bigdata == "企業管理相關 " |
                vec_dep_bigdata == "一般商業學類" |
                vec_dep_bigdata == "會計學相關" |
                vec_dep_bigdata == "企業管理相關" |
                vec_dep_bigdata == "市場行銷相關"] <- "其他商業及管理相關"
vec_dep_bigdata[vec_dep_bigdata == " 經濟學相關" |
                vec_dep_bigdata == "經濟學相關" |
                vec_dep_bigdata == "經濟社會及心理學科類 "] <- "經濟社會及心理學科類"
vec_dep_bigdata[vec_dep_bigdata == "工業工程相關"] <- "工程相關"
vec_dep_bigdata[vec_dep_bigdata == "生物學相關" |
                vec_dep_bigdata == "食品科學相關" |
                vec_dep_bigdata == "公共衛生相關" |
                vec_dep_bigdata == "大眾傳播學科類" |
                vec_dep_bigdata == "地理學相關" |
                vec_dep_bigdata == "建築及都市規劃學科類"] <- "其他專業學科"
vec_dep_bigdata[vec_dep_bigdata == " 不拘 "] <- "不拘"


bigdatadt <- data.table(bigdata)
bigdata_m <- bigdatadt[grepl('月薪',salary)] #將年薪資料去除

##建立提及次數dataframe
df_dep_bigdata <- data.frame(table(vec_dep_bigdata))
df_dep_bigdata <- df_dep_bigdata %>%
    arrange(desc(Freq)) %>%
    mutate(perc = round(Freq/sum(Freq)*100)) %>%
    rename(科系 = vec_dep_bigdata)
View(df_dep_bigdata)
##作長條圖
bigdata_bar <- ggplot(df_dep_bigdata) +
    geom_bar(aes(x = perc , y = reorder(科系, -perc)), stat = "identity") +
    labs(x = "百分比(%)", y = "科系", title = "大數據工程師科系要求") +
    theme(text=element_text(family="STHeiti", size=14))

plotly::ggplotly(bigdata_bar)
```


## 大數據工程師工具
   
```{r}
plotly::ggplotly(bigdata_bar_t)
```
   

三種工程師薪水比較圖
=========================
  
```{r}
##將月薪轉換成數字

vec_sal_product <- as.numeric(substr(product_m$salary,3, 4))

vec_sal_back <- as.numeric(substr(back_m$salary,3, 4))
vec_sal_back[vec_sal_back == 10] <- 100
 
vec_sal_bigdata <- as.numeric(substr(bigdata_m$salary,3, 4))

##製作有無科系要求之向量

vec_dep_product1 <- product_m$department
vec_dep_product1[vec_dep_product1 == "不拘"] <- "無"
vec_dep_product1[vec_dep_product1 != "無"] <- "有"

vec_dep_back1 <- back_m$department
vec_dep_back1[vec_dep_back1 == "不拘"] <- "無"
vec_dep_back1[vec_dep_back1 != "無"] <- "有"

vec_dep_bigdata1 <- bigdata_m$department
vec_dep_bigdata1[vec_dep_bigdata1 == "不拘"] <- "無"
vec_dep_bigdata1[vec_dep_bigdata1 != "無"] <- "有"

job <- vector("character", 354) 
for (i in(1:354)) {
    if(i<= 132) {
        job[i] <- "前端工程師"
    }
    if(i>132 & i<= 267) {
        job[i] <- "後端工程師"
    }
    if(i>267) {
        job[i] <- "大數據分析工程師"
    }
}

df_sal <- data.frame(Job = job,
                     Department = c(vec_dep_product1,
                                      vec_dep_back1,
                                      vec_dep_bigdata1),
                     Salary = c(vec_sal_product,
                                vec_sal_back,
                                vec_sal_bigdata))

df_sal1 <- df_sal %>%
    group_by(Job, Salary) %>%
    summarise(n = n()) %>%
    mutate(cumulative_ratio = cumsum(n/sum(n)*100))

salary_line <- ggplot(df_sal1, aes(Salary, cumulative_ratio, group = Job, colour = Job)) +
    geom_line(size = 1.2) +scale_fill_brewer(palette = "Pastel1") +
    labs(x = "月薪(單位:千元)", y = "累積百分比(%)", title = "薪水比較") +
    theme(text=element_text(family="STHeiti", size=14))


plotly::ggplotly(salary_line)

```

  
Boxplot
=========================

## 科系要求和薪資
  
```{r}
dep_boxplot <- ggplot(df_sal, aes(x = Job, y = Salary, fill = Department)) +
    geom_boxplot() +
    facet_wrap(~Job, scale="free") +
    labs(y = "月薪(單位:千元)", fill = "科系要求", title = "科系要求薪水比較") +
    theme(text=element_text(family="STHeiti", size=14))

dep_boxplot
```


## 工具要求和薪資

  
```{r}
dep_boxplot_t
```

